### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by OmorOrNot** [Riot-Byte/aphrobyte-rat#4]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 181, in <module>
  File "cv2\__init__.py", line 76, in bootstrap
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

**Comment by Riot-Byte** [comment]
whats ur python version
